print("I’m planning to learn git conflicts resolution")
nickname = input("Please enter your nickname")
name = input("Please enter your name:")
surname = input("Please enter your surname:")
print("Hi, {} {}! a.k.a {}".format(name, surname, nickname))
